import type { Package } from '@/types/package'

export const laravelPackages: Package[] = [
    {
        name: 'Laravel Auditing',
        description: 'Understand changes in Eloquent models.',
        category: 'Database & Eloquent',
        github: 'https://github.com/owen-it/laravel-auditing',
        composer: 'owen-it/laravel-auditing',
        author: 'owen-it',
        stars: 2568,
        keywords: [],
        first_release_at: '2015-08-20T11:45:08+00:00',
        latest_release_at: '2023-03-17T11:39:04+00:00',
    },
    {
        name: 'Laravel Media Library',
        description: 'Associate files with eloquent models.',
        category: 'File Management',
        github: 'https://github.com/spatie/laravel-medialibrary',
        composer: 'spatie/laravel-medialibrary',
        author: 'spatie',
        stars: 5288,
        keywords: [],
        first_release_at: '2015-04-14T09:07:29+00:00',
        latest_release_at: '2023-03-06T11:26:25+00:00',
    },
    {
        name: 'Laravel Permissions',
        description: 'Associate users with roles and permissions.',
        category: 'Auth & Permissions',
        github: 'https://github.com/spatie/laravel-permission',
        composer: 'spatie/laravel-permission',
        author: 'spatie',
        stars: 11105,
        keywords: [],
        first_release_at: '2015-09-15T15:36:13+00:00',
        latest_release_at: '2023-03-22T02:57:36+00:00',
    },
    {
        name: 'Laravel Debugbar',
        description: 'This is a package to integrate PHP Debug Bar with Laravel.',
        category: 'Debugging & Dev Tools',
        github: 'https://github.com/barryvdh/laravel-debugbar',
        composer: 'barryvdh/laravel-debugbar',
        author: 'barryvdh',
        stars: 15036,
        keywords: [],
        first_release_at: '2013-09-05T10:33:08+00:00',
        latest_release_at: '2023-02-21T14:21:02+00:00',
    },
    {
        name: 'Laravel Backup',
        description: 'A package to backup your Laravel app.',
        category: 'Dev Ops',
        github: 'https://github.com/spatie/laravel-backup',
        composer: 'spatie/laravel-backup',
        author: 'spatie',
        stars: 5194,
        keywords: [],
        first_release_at: '2015-02-17T16:21:56+00:00',
        latest_release_at: '2023-02-03T15:57:49+00:00',
    },
    {
        name: 'Laravel Localization',
        description: 'Easy i18n localization for Laravel, an useful tool to combine with Laravel localization classes.',
        category: 'Localization',
        github: 'https://github.com/mcamara/laravel-localization',
        composer: 'mcamara/laravel-localization',
        author: 'mcamara',
        stars: 3109,
        keywords: [],
        first_release_at: '2013-09-01T19:17:57+00:00',
        latest_release_at: '2023-02-18T15:43:23+00:00',
    },
    {
        name: 'Laravel GraphQL',
        description: 'Laravel wrapper for Facebooks GraphQL',
        category: 'API',
        github: 'https://github.com/rebing/graphql-laravel',
        composer: 'rebing/graphql-laravel',
        author: 'rebing',
        stars: 1957,
        keywords: [],
        first_release_at: '2016-09-19T10:55:53+00:00',
        latest_release_at: '2023-03-05T15:42:39+00:00',
    },
    {
        name: 'Laravel SEO',
        description: 'A package to handle the SEO in any Laravel application, big or small.',
        category: 'SEO',
        github: 'https://github.com/ralphjsmit/laravel-seo',
        composer: 'ralphjsmit/laravel-seo',
        author: 'ralphjsmit',
        stars: 317,
        keywords: [],
        first_release_at: '2022-02-08T13:33:02+00:00',
        latest_release_at: '2023-02-17T17:52:50+00:00',
    },
    {
        name: 'Pest',
        description: 'An elegant PHP testing Framework with a focus on simplicity.',
        category: 'Testing',
        github: 'https://github.com/pestphp/pest',
        composer: 'pestphp/pest',
        author: 'pestphp',
        stars: 6648,
        keywords: [],
        first_release_at: '2020-05-19T23:10:29+00:00',
        latest_release_at: '2023-03-28T09:16:29+00:00',
    },
    {
        name: 'Laravel Cashier',
        description: 'An expressive, fluent interface to Stripe subscription billing services.',
        category: 'Payment',
        github: 'https://github.com/laravel/cashier-stripe',
        composer: 'laravel/cashier',
        author: 'laravel',
        stars: 2209,
        keywords: [],
        first_release_at: '2014-03-04T03:21:19+00:00',
        latest_release_at: '2023-03-02T16:11:43+00:00',
    },
    {
        name: 'Laravel Honeypot',
        description: 'Preventing spam submitted through forms.',
        category: 'Security',
        github: 'https://github.com/spatie/laravel-honeypot',
        composer: 'spatie/laravel-honeypot',
        author: 'spatie',
        stars: 1097,
        keywords: [],
        first_release_at: '2018-12-27T08:58:24+00:00',
        latest_release_at: '2023-01-17T07:09:34+00:00',
    },
    {
        name: 'Laravel Mail Preview',
        description: 'A mail driver to quickly preview mail.',
        category: 'Mail',
        github: 'https://github.com/spatie/laravel-mail-preview',
        composer: 'spatie/laravel-mail-preview',
        author: 'spatie',
        stars: 1043,
        keywords: [],
        first_release_at: '2021-01-27T17:19:36+00:00',
        latest_release_at: '2023-01-25T15:10:45+00:00',
    },
    {
        name: 'Aimeos',
        description: 'Ultra fast online shops, scalable marketplaces, complex B2B applications and Gigacommerce.',
        category: 'E-Commerce',
        github: 'https://github.com/aimeos/aimeos-laravel',
        composer: 'aimeos/aimeos-laravel',
        author: 'aimeos',
        stars: 6088,
        keywords: [],
        first_release_at: '2015-03-06T14:24:42+00:00',
        latest_release_at: '2023-02-16T09:59:16+00:00',
    },
    {
        name: 'Filament',
        description: 'Admin panel, form builder and table builder for Laravel. Built with the TALL stack. Designed for humans.',
        category: 'CMS & Admin Panels',
        github: 'https://github.com/filamentphp/filament',
        composer: 'filament/filament',
        author: 'filamentphp',
        stars: 6180,
        keywords: [],
        first_release_at: '2020-04-28T19:14:44+00:00',
        latest_release_at: '2023-03-25T17:36:34+00:00',
    },
    {
        name: 'Laravel Actions',
        description: 'Organising the logic of your Laravel applications by focusing on the actions your applications provide.',
        category: 'Code Architecture',
        github: 'https://github.com/lorisleiva/laravel-actions',
        composer: 'lorisleiva/laravel-actions',
        author: 'lorisleiva',
        stars: 2023,
        keywords: [],
        first_release_at: '2019-05-19T19:19:13+00:00',
        latest_release_at: '2023-02-22T10:37:59+00:00',
    },
    {
        name: 'Flash',
        description: 'Offers a Twitter Bootstrap optimized flash messaging setup',
        category: 'Notifications',
        github: 'https://github.com/laracasts/flash',
        composer: 'laracasts/flash',
        author: 'laracasts',
        stars: 2602,
        keywords: [],
        first_release_at: '2014-06-30T04:07:13+00:00',
        latest_release_at: '2023-01-30T20:31:40+00:00',
    },
    {
        name: 'Blade Icons',
        description: 'Easily make use of SVG icons in your Laravel Blade views.',
        category: 'UI & Blade Components',
        github: 'https://github.com/blade-ui-kit/blade-icons',
        composer: 'blade-ui-kit/blade-icons',
        author: 'blade-ui-kit',
        stars: 1768,
        keywords: [],
        first_release_at: '2020-06-17T18:38:25+00:00',
        latest_release_at: '2023-02-15T16:30:12+00:00',
    },
    {
        name: 'Laravel Tags',
        description: 'Add tags and taggable behaviour to your Laravel app.',
        category: 'Utilities & Helpers',
        github: 'https://github.com/spatie/laravel-tags',
        composer: 'spatie/laravel-tags',
        author: 'spatie',
        stars: 1397,
        keywords: [],
        first_release_at: '2016-10-19T08:47:17+00:00',
        latest_release_at: '2023-01-25T09:12:48+00:00',
    },
]
